---
title: "Modul3-Tapsiriq4"
output: html_document
date: "2023-05-05"
---

```{r setup, include=FALSE}
library(tidyverse)
require(ggplot2)
library(inspectdf)
library(naniar)
library(correlationfunnel)
```

#### 1. "data <- ggplot2::msleep" kodunu icra et. datanın "NA" faizlərini plotla göstər.

```{r}
data <- ggplot2::msleep
data %>% inspect_na() %>% show_plot()
```

#### 2. datada correlasiyaları plotla göstər.



```{r}
data %>%  inspect_cor() %>% show_plot()
```

#### 3. datada ortaq "NA"ləri plotla göstər.



```{r}
data %>% gg_miss_upset()
```


#### 4. "data <- "correlationfunnel::marketing_campaign_tbl" kodunu icra et. datada dəyişənlərin "TERM_DEPOSIT" dəyişəninin"yes" dəyəri ilə olan korrelasiyalarını interaktiv plotla göstər.



```{r}
data = correlationfunnel::marketing_campaign_tbl %>% binarize(one_hot = T)
correlation = data %>% correlate(target = TERM_DEPOSIT__yes)

correlation %>% plot_correlation_funnel(interactive=T)
```
